apiVersion: v2
appVersion: 10.5.9447
description: A Helm chart for Kubernetes
name: webcerberus
version: 10.5.9447


dependencies:
  - name: solr
    version: 0.9.1
    repository: https://solr.apache.org/charts
  - name: solr-operator
    version: 0.9.1
    repository: https://solr.apache.org/charts
    condition: solrOperator.install