apiVersion: v2
appVersion: 583
description: A Helm chart for Kubernetes
name: webcerberus
version: 8.1.8518.1

dependencies:
  - name: solr
    version: 6.3.x
    repository: https://charts.bitnami.com/bitnami
